/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:31e73415-c350-43ba-b0b1-80c79c964d98",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_9fLoO5YN8",
    "aws_user_pools_web_client_id": "9m3lusa56lgttv1liis3eejil",
    "oauth": {}
};


export default awsmobile;
